### ISSUE TITLE
Replace Temporary.swift with standard SPM solution?

### ISSUE THREAD

**Issue by bachand** [fdiaz/SwiftInspector#16]
I haven't dug into this super far but I think there's an opportunity to simplify.

<img width="956" alt="Screen Shot 2020-03-30 at 4 06 42 PM" src="https://user-images.githubusercontent.com/1791049/77970273-9ea26c80-72a0-11ea-8dee-09cf76b8a3e1.png">

https://nshipster.com/swiftsyntax/

**Comment by fdiaz** [comment]
I'm not sure we want to pull the whole SPM library just to create temporary files for testing honestly.

**Comment by bachand** [comment]
That’s a good point. And actually when I skimmed the argument parser post it talked about how people were using something internal to SPM that wasn’t really meant to be widely used. Seems related. I’ll close
