### ISSUE TITLE
Have a way to define the type of the initializer

### ISSUE THREAD

**Issue by fdiaz** [fdiaz/SwiftInspector#23]
There are multiple types of parameters used in an initializer in Swift:

1. A simple type -- e.g. `init(some: Int)`
2. A composition of types e.g. `init(some: Decodable & Encodable)`
3. A tuple: e.g. `init(some: (String, Int)`
4. A closure -- e.g. `init(someHandler: () -> Void)`

We should have a way to differentiate between these in the `InitializerStatement.Parameter` and also to output to std output when the users wants to.

**Comment by dfed** [comment]
I think `TypeDescription` handles these cases pretty well/explicitly. Thoughts on closing this out as resolved? Or do we need to adopt `TypeDescription` elsewhere?

**Comment by fdiaz** [comment]
You're right, we're handling this now 😉
